### ISSUE TITLE
todo options for prepare config

### ISSUE THREAD

**Issue by GitScrum** [posthtml/posthtml-load-plugins#34]
- [ ] get custome namespace
- [ ] cut namespace
- [ ] transform to snake-case (now default) or outher case

**Comment by GitScrum** [comment]
thoughts about sequence options
[function([sequence-config])] 
- [ ] [function([sequence-config])] - outher sorter,argument sequence-config now used default  posthtml-sequence-config
